### ISSUE TITLE
Linkify fails on somewhat malformed HTML

### ISSUE THREAD

**Issue by rmihael** [jsocol/bleach#160]
We are using linkify (version 1.4.1) to highligh links in email messages and one message caused the following error:

```
Traceback (most recent call last):
  File "...", line 420, in _make_text_html_bodies
    body = linkify(body)
  File "/media/ephemeral0/nimble/eggs/bleach-1.4.1-py2.7.egg/bleach/__init__.py", line 359, in linkify
    linkify_nodes(forest)
  File "/media/ephemeral0/nimble/eggs/bleach-1.4.1-py2.7.egg/bleach/__init__.py", line 298, in linkify_nodes
    linkify_nodes(node, True)
  File "/media/ephemeral0/nimble/eggs/bleach-1.4.1-py2.7.egg/bleach/__init__.py", line 298, in linkify_nodes
    linkify_nodes(node, True)
  File "/media/ephemeral0/nimble/eggs/bleach-1.4.1-py2.7.egg/bleach/__init__.py", line 263, in linkify_nodes
    adj = replace_nodes(tree, new_tail, None, current_child+1)
  File "/media/ephemeral0/nimble/eggs/bleach-1.4.1-py2.7.egg/bleach/__init__.py", line 148, in replace_nodes
    tree.text += new_tree.text
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'unicode'
```

I managed to reduce message to a minimal error-reproducing case:
```python
from bleach import linkify
body = """
<div><br>
    <meta name="generator" content="www.coffeecup.com">
</div>"""
linkify(body)
```

I guess it may have something with the fact that `meta` tags are not allowed in `div`. Unfortunately it happens in a wild.

**Comment by jsocol** [comment]
Have you tried this with master? It sounds similar to #136

**Comment by rmihael** [comment]
It works with master. Sorry for bothering you. May I ask if you plan to release another version anytime soon?

**Comment by MadSpindel** [comment]
@jsocol Please provide new pip package from master.

**Comment by rmihael** [comment]
Looks like this problem is gone with release of 1.4.2.
